name: skeleton_animation
description: Display skeleton animations in your app. It works on android, iOS and the web.
version: 0.1.5
repository: https://github.com/wjtje/flutter-skeleton-animation

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
